[package]
name = "eldegoss"
version = "0.1.0"
edition = "2021"
description = "eldegoss net"
readme = "README.md"
repository = "https://github.com/JLerxky/eldegoss"
license = "Apache-2.0"
authors = ["JLer <jlerxky@live.com>"]
categories = ["network"]
keywords = ["network", "p2p", "gossip", "SWIM"]

[features]
default = []

[dependencies]
bincode = "1.3"
color-eyre = "0.6"
common_x = { version = "0.1", default-features = false, features = [
    "cert",
    "log",
], path = "../common_x" }
flume = "0.11"
parking_lot = "0.12"
quinn = "0.10"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.34", features = ["full"] }
tracing = "0.1"

[profile.dev]
debug = 0
opt-level = 3

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = "thin"
opt-level = "s"
codegen-units = 1

[workspace.lints.rust]
unsafe_code = "forbid"
missing_copy_implementations = "warn"
missing_debug_implementations = "warn"
unused_crate_dependencies = "warn"
unused_extern_crates = "warn"

[workspace.lints.clippy]
missing_const_for_fn = "warn"
