[package]
name = "eldegoss"
version = "0.1.1"
edition = "2021"
description = "eldegoss net"
readme = "README.md"
repository = "https://github.com/JLerxky/eldegoss"
license = "Apache-2.0"
authors = ["JLer <jlerxky@live.com>"]
categories = ["network-programming"]
keywords = ["network", "p2p", "gossip", "SWIM"]

[features]
default = []

[dependencies]
bincode = "1.3"
bitflags = "2.4"
clap = { version = "4.4", features = ["derive"] }
color-eyre = "0.6"
common_x = { version = "0.3", default-features = false, features = [
    "cert",
    "config",
    "log",
    "signal",
] }
flume = "0.11"
futures = "0.3"
hex = "0.4"
quinn = "0.10"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.34", features = ["full"] }
tracing = "0.1"
uhlc = "0.6"

[dev-dependencies]
ractor = "0.9"
rkyv = "0.7"

[profile.dev]
debug = true
opt-level = 0

[profile.fast]
inherits = "release"
opt-level = 3
debug = true
debug-assertions = true
overflow-checks = true
lto = false

[profile.release]
debug = false
lto = "fat"
codegen-units = 1
opt-level = 3
panic = "abort"

[lints.rust]
# unsafe_code = "forbid"
# missing_copy_implementations = "warn"
# missing_debug_implementations = "warn"
# unused_crate_dependencies = "warn"
unused_extern_crates = "warn"

[lints.clippy]
missing_const_for_fn = "warn"
