id = "0000000000000000000000000000000c"
listen = "[::]:9002"
connect = ["127.0.0.1:9000", "127.0.0.1:9001"]
cert_path = "./config/cert/client_cert.pem"
private_key_path = "./config/cert/client_key.pem"
ca_path = "./config/cert/ca_cert.pem"
subscription_list = ["topic"]
